// Copyright (c) 2021 Xiaozhe Yao et al.
// 
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

[[models]]
name = "cnn-pt"
url = "https://github.com/aidmodels/sentiment-pytorch/releases/download/v0.0.1/imdb-model-cnn.pt"

[[models]]
name = "glove-6b-300d"
url = "https://github.com/aidmodels/sentiment-pytorch/releases/download/v0.0.1/glove.6B.100d.txt"